layout: resize the filesystem after expanding it
mudler/yip pull request #23
Opened 2021-09-27 19:18 UTC by Itxaka

Signed-off-by: Itxaka <igarcia@suse.com>

2021-09-28 11:27 UTC, Itxaka commented
@davidcassany could you have a look at this? I think its the correct approach to the resizing but Im not sure about it.

2021-09-28 13:52 UTC, davidcassany requested changes
This is correct but not complete.

Note this plugin supports ext[2-4] and xfs filesystems. So in case of an XFS partition it should call `xfs_growfs -d <device>`. You can use `blkid` tool to detect the underlaying filesystem.

I included XFS support mostly because I see this plugin creating the persistent partition which is likely to make use of a modern filesystem such as XFS.

Finally in addition, to make this changes effective in cOS note that immutable rootfs must include any new executable that layout plugin might call (`resize2fs`, `xfs_growfs`). See:
https://github.com/rancher-sandbox/cOS-toolkit/blob/0b3d79b22e5b09644fa91bf2253a5bf3252a5eec/packages/immutable-rootfs/30cos-immutable-rootfs/module-setup.sh#L29-L32

2021-09-29 14:47 UTC, Itxaka commented
@davidcassany @mudler ready for review!

2021-09-30 07:12 UTC, davidcassany approved these changes
LGTM

2021-09-30 07:12 UTC, davidcassany commented on pkg/plugins/layout.go
> +		// to grow an xfs fs it needs to be mounted :/
Ouch, this is unfortunate

2021-09-30 07:16 UTC, mudler approved these changes

2021-09-30 07:16 UTC, merged